name: Build Rpm File

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:44
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: target
          path: ./target/

      - run: sudo dnf install -y rpmdevtools rpmlint pandoc tree
      - run: ./scripts/build-rpms.sh

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f  # v7.0.0
        with:
          name: rpm-deliverables
          path: |
            ./*.rpm
            ./*.rpm.*sum

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f  # v7.0.0
        with:
          name: rpm-working-files
          path: ~/rpmbuild/
