name: Deploy GitHub Release Assets

on:
  workflow_call:
    secrets:
      TOKEN_TO_UPLOAD_ASSETS:
        required: true

jobs:
  deploy_github_release_assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          name: deb-deliverables
          path: ./
      - uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          name: rpm-deliverables
          path: ./
      - uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          name: target
          path: ./target/

      - run: ls -l

      - uses: svenstaro/upload-release-action@6b7fa9f267e90b50a19fef07b3596790bb941741 # 2.11.3
        with:
          repo_token: ${{ secrets.TOKEN_TO_UPLOAD_ASSETS }}
          file_glob: true
          file: ./*.deb
      - uses: svenstaro/upload-release-action@6b7fa9f267e90b50a19fef07b3596790bb941741 # 2.11.3
        with:
          repo_token: ${{ secrets.TOKEN_TO_UPLOAD_ASSETS }}
          file_glob: true
          file: ./*.deb.sha256sum
      - uses: svenstaro/upload-release-action@6b7fa9f267e90b50a19fef07b3596790bb941741 # 2.11.3
        with:
          repo_token: ${{ secrets.TOKEN_TO_UPLOAD_ASSETS }}
          file_glob: true
          file: ./*.deb.sha512sum
      - uses: svenstaro/upload-release-action@6b7fa9f267e90b50a19fef07b3596790bb941741 # 2.11.3
        with:
          repo_token: ${{ secrets.TOKEN_TO_UPLOAD_ASSETS }}
          file_glob: true
          file: ./target/*.jar
      - uses: svenstaro/upload-release-action@6b7fa9f267e90b50a19fef07b3596790bb941741 # 2.11.3
        with:
          repo_token: ${{ secrets.TOKEN_TO_UPLOAD_ASSETS }}
          file_glob: true
          file: ./*.rpm
      - uses: svenstaro/upload-release-action@6b7fa9f267e90b50a19fef07b3596790bb941741 # 2.11.3
        with:
          repo_token: ${{ secrets.TOKEN_TO_UPLOAD_ASSETS }}
          file_glob: true
          file: ./*.rpm.sha256sum
      - uses: svenstaro/upload-release-action@6b7fa9f267e90b50a19fef07b3596790bb941741 # 2.11.3
        with:
          repo_token: ${{ secrets.TOKEN_TO_UPLOAD_ASSETS }}
          file_glob: true
          file: ./*.rpm.sha512sum
