name: Qlty.sh

on:
  workflow_call:
    secrets:
      QLTY_COVERAGE_TOKEN:
        required: true

jobs:
  QltySh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          name: target
          path: ./target/

      - run: .github/bin/qlty-coverage-publish.sh
        env:
          QLTY_COVERAGE_TOKEN: ${{ secrets.QLTY_COVERAGE_TOKEN }}
